[package]
name = "backwards-compat"
version = "0.2.0"
edition = "2024"
description = "Streamlined backwards compatibility and schema versioning for Serde"
license = "MIT OR Apache-2.0"

[workspace]
members = [
    ".",
    "derive",
]

[dependencies]
backwards-compat-derive = { path = "derive", version = "0.2.0" }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ron = "0.12"
toml = "1.1"
thiserror = "2.0"
