name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: Build, Test & Coverage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        components: clippy, rustfmt, llvm-tools

    - name: Check Formatting
      run: cargo fmt --check

    - name: Lint (Clippy)
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Build Release
      run: cargo build --all --release

    - name: Install Cargo LLVM Cov
      uses: baptiste0928/cargo-install@v3
      with:
        crate: cargo-llvm-cov

    - name: Run Tests & Generate Coverage
      run: cargo llvm-cov test --all-features --workspace --lcov --output-path lcov_raw.info

    - name: Filter and Format Coverages
      run: chmod +x .github/workflows/coverages.bash && .github/workflows/coverages.bash

    - name: Upload LCOV Artifact
      uses: actions/upload-artifact@v4
      with:
        name: lcov-coverage
        path: lcov.info
        retention-days: 7

    - name: Print Coverage to Job Summary
      uses: livewing/lcov-job-summary@v1.3.0
      with:
        lcov: lcov.info
